### ISSUE TITLE
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work.

### ISSUE THREAD

**Issue by Staubgeborener** [Sorrow446/HLAT-Hogwarts-Legacy-Appearance-Tool#2]
Running the pre compiled executable leads to a panic error:

```cmd
C:\Windows\system32>C:\Users\user\hlat_x86.exe export -i C:\Users\user\AppData\Local\Hogwarts\Saved\SaveGames\46503878\HL-00-00.sav -o C:\Users\user\AppData\Local\Hogwarts\Saved\SaveGames\46503878\eve.json
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
main.main()
        G:/go/hlat/main.go:321 +0x27e

```

Building the source code by my own including go-sqlite3 didn't resolve it:

```cmd
C:\Users\user\Downloads\HLAT-Hogwarts-Legacy-Appearance-Tool-1>go get github.com/mattn/go-sqlite3

C:\Users\user\Downloads\HLAT-Hogwarts-Legacy-Appearance-Tool-1>go build

C:\Users\user\Downloads\HLAT-Hogwarts-Legacy-Appearance-Tool-1>main export -i C:\Users\user\AppData\Local\Hogwarts\Saved\SaveGames\46503878\HL-00-00.sav -o C:\Users\user\AppData\Local\Hogwarts\Saved\SaveGames\46503878\eve.json
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
main.main()
        C:/Users/user/Downloads/HLAT-Hogwarts-Legacy-Appearance-Tool-1/main.go:321 +0x208
```

The executable, which is downloadable at [nexusmods](https://www.nexusmods.com/hogwartslegacy/mods/72?tab=description) is working fine.

**Comment by Sorrow446** [comment]
The binaries on here are identical to those on Nexus so GitHub might be corrupting them. Use x64 instead if you can.

**Comment by Staubgeborener** [comment]
Doesn't matter if I use x64 or x86. But I will close this issue.
